classDiagram
    
    class Customer {
        long id
        Name customerName
        Age age
        Email email
    }

    class BaseEntity {
        String createdAt
        String updatedAt
    }

    Customer --> BaseEntity