version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    volumes:
      - "data_volume:/var/lib/mysql"
    environment:
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "weeklyjpa"
volumes:
  data_volume: