
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: false
      dialect: org.hibernate.dialect.H2Dialect
    database: h2