spring :
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/test
      username: sa
      password:
  jpa:
    generate-ddl: true  #ddl option
    open-in-view: false
    show-sql: true    #sql 쿼리 확인